name: py-env-1
channels:
  - conda-forge
dependencies:
  - pytest
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - hvplot
  - intake
  - fsspec
  - gcsfs
  - tqdm
  - pip
  - zarr
  - pip:
      - ghp-import
      - sounddevice
      - soundfile
      - sparse
      - wget
      - xapres
